version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DOCKER_MACHINE_IP=0.0.0.0
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postrgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "no" ]
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data